fix: add unique id to app created page
getAlby/hub pull request #257
Opened 2024-07-11 09:44 UTC by reneaaron

Fixes #252 

State seems to be persisted in browsers history, we fix that by using a unique URI for every app that has been created.

2024-07-11 10:04 UTC, im-adithya approved these changes
Nice 🙌

2024-07-11 10:12 UTC, im-adithya commented
Did you try passing `{ state: null }` after we go to /apps on having lastEventAt [here](https://github.com/getAlby/hub/blob/master/frontend/src/screens/apps/AppCreated.tsx#L56)? I can't reproduce even the actual issue

2024-07-12 03:18 UTC, rolznz commented on frontend/src/screens/apps/NewApp.tsx
> +        `/apps/created?id=${createAppResponse.pairingPublicKey}${app ? `&app=${app.id}` : ""}`,
It was already here, but why is there a conditional here? this seems wrong?

Also, the `pairingPublicKey` should be unique per app

2024-07-12 03:19 UTC, rolznz requested changes
something is wrong here (not sure what)

2024-07-13 06:09 UTC, rolznz commented on frontend/src/screens/apps/NewApp.tsx
> +        `/apps/created?id=${createAppResponse.pairingPublicKey}${app ? `&app=${app.id}` : ""}`,
sorry, I completely misread this. I am wrong :cry:

2024-07-13 06:13 UTC, rolznz commented on frontend/src/screens/apps/NewApp.tsx
> +        `/apps/created?id=${createAppResponse.pairingPublicKey}${app ? `&app=${app.id}` : ""}`,
but it's weird, the navigation state should work. And it seems like it's not

2024-07-13 06:39 UTC, rolznz commented
@im-adithya @reneaaron I found how to consistently reproduce the issue:

1. Create a new app and do at least one NWC event for it
2. Delete the app
3. Create a new app

Step 3. Will lead to this bug.

The pubkey is different for each app, but SQLITE is reusing app IDs rather than properly auto-incrementing.

We fetch events by pubkey from the API, but internally we query by app ID.

And for some reason when we delete apps, the request_events are not deleted.

So this PR does actually not fix the issue, and there's nothing wrong with the routing (which passes different state each time)

2024-07-13 06:45 UTC, rolznz commented
For some reason the foreign key on delete constraint is not working

```
sqlite> .schema request_events
CREATE TABLE IF NOT EXISTS "request_events" (`id` integer,`app_id` integer null,`nostr_id` text UNIQUE,`state` text,`created_at` datetime,`updated_at` datetime, method TEXT, content_data TEXT,PRIMARY KEY (`id`),CONSTRAINT `fk_request_events_app` FOREIGN KEY (`app_id`) REFERENCES `apps`(`id`) ON DELETE CASCADE);
CREATE UNIQUE INDEX `idx_request_events_nostr_id` ON `request_events`(`nostr_id`);
CREATE INDEX `idx_request_events_app_id` ON `request_events`(`app_id`);
CREATE INDEX idx_request_events_app_id_and_id ON request_events(app_id, id);
CREATE INDEX `idx_request_events_method` ON `request_events`(`method`);
```

2024-07-13 07:32 UTC, closed without merging